version: '3.8'
services:
  api:
    build:
      context: ./
      target: dev
    volumes:
      - .:/src
    command: npm start
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: dev
    depends_on:
      - "mongodb"
  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: 1234
    ports:
      - "4000:27017"
    volumes:
      - "mongodb_data:/data/db"

volumes:
  mongodb_data: