version: '3.8'
services:
  api:
    build:
      context: ./
      target: dev
    volumes:
      - .:/src
    command: npm start
    ports:
      - "${API_EXPOSE_PORT}:3000"
    environment:
      NODE_ENV: dev
    depends_on:
      - "mongodb"
  mongodb:
    image: mongo:latest
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_ROOT_PASSWORD}
    ports:
      - "${MONGODB_EXPOSE_PORT}:27017"
    volumes:
      - "mongodb_data:/data/db"

volumes:
  mongodb_data: